# Generated by Django 4.2 on 2024-05-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('pending', 'Pending'), ('published', 'Published'), ('reject', 'Reject')], max_length=20),
        ),
    ]
