# Generated by Django 4.2 on 2024-07-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_alter_map_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/Default-thum.png', upload_to='thumbnails/'),
        ),
    ]
