# Generated by Django 4.2 on 2024-11-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0007_alter_notification_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
