# Generated by Django 4.2 on 2024-12-31 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0008_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Hex code of the color (e.g. #FFFFFF for white).', max_length=7)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='Map.map')),
            ],
            options={
                'verbose_name': 'Map Color',
                'verbose_name_plural': 'Map Colors',
            },
        ),
    ]
