# Generated by Django 4.2 on 2024-12-31 03:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0009_mapcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcolor',
            name='color',
            field=colorfield.fields.ColorField(default='#007279', image_field=None, max_length=25, samples=None),
        ),
    ]
