# Generated by Django 4.2 on 2024-12-31 04:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0010_alter_mapcolor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcolor',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
