# Generated by Django 4.2 on 2024-12-31 05:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0011_alter_mapcolor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcolor',
            name='color',
            field=colorfield.fields.ColorField(default='#007279', image_field=None, max_length=25, samples=[('#000000', 'black'), ('#FF0000', 'red'), ('#00FF00', 'green'), ('#0000FF', 'blue'), ('#FFFF00', 'yellow'), ('#00FFFF', 'cyan'), ('#FF00FF', 'magenta'), ('#800080', 'purple'), ('#FFA500', 'orange')]),
        ),
    ]
