# Generated by Django 4.2 on 2025-01-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0012_alter_mapcolor_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['-publishing_date']},
        ),
    ]
