# Generated by Django 4.2 on 2025-10-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0013_alter_map_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={},
        ),
    ]
