# Generated by Django 4.2 on 2025-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
